### ISSUE TITLE
Check Move is Legal

### ISSUE THREAD

**Issue by Maeggi** [ryanhs/chess.php#2]
Hello,
i am using chess.js. What is the best Way to check, move is Legal?.  Server Side , on your library?
Thx

**Comment by ryanhs** [comment]
hey.. you can import the fen/pgn in chess.php (you record everymove right?) and check all legal moves.

thanks

**Comment by Maeggi** [comment]
hey, tahnks for your answer. i transfer the move over ajax (post). i search a function: check the move. is move legal, then saved in db :) that is my plan :)

**Comment by ryanhs** [comment]
oke, good luck ;-)
