### ISSUE TITLE
Type hinting

### ISSUE THREAD

**Issue by garak** [ryanhs/chess.php#6]
I see this project has a minimum requirement of php 7.2, so it would be nice to get some type hinting (and return types, of course)

**Comment by Kooser6** [comment]
Ill create a pull request, if no response ill fork and maintain the project.

**Comment by ryanhs** [comment]
Okay Nicholas, i approve PR when you submit one . sorry currently I have
hectic schedule to work on something else

**Comment by Kooser6** [comment]
No problem.

**Comment by DaanBiesterbos** [comment]
For a non OOP this code looks decent. But for code completion, return types etc you need types to begin with. There are no models, there is also quite some business logic and concerns that deserve their own class and interface. To get typehinting I would say this code needs to be refactored. That is OK. Please don't get me wrong, I greatly appreciate the work that Ryan has put into it and I don't think it is bad either.  It can be further improved though :+1:  How complete is this implementation? This might be something I can use for a personal project. And if I do I don't mind to refactor the code and give it back.

**Comment by ryanhs** [comment]
@DaanBiesterbos yes sure Daan, PR are welcome :-)
the goal of chess logic mostly done for this project, due to there is no need to put AI in chess logic.

**Comment by lovephpforever** [comment]
Merged.

**Comment by garak** [comment]
@DaanBiesterbos if you look to a better implementation, see https://github.com/p-chess/chess
